### ISSUE TITLE
Prefix support

### ISSUE THREAD

**Issue by temoto** [peterbourgon/g2s#6]
Please, consider prefix feature from https://github.com/cactus/go-statsd-client
it adds a prefix to all bucket names.

**Comment by tleyden** [comment]
I ran into this issue too while trying to use https://www.hostedgraphite.com:


> Send StatsD-formatted data to statsd.hostedgraphite.com:8125
> Prefix any data with your Hosted Graphite API Key (fc92...).
> Most clients accept a 'prefix' or 'namespace' option to allow you to include your API key.

**Comment by FranGM** [comment]
Hosted Graphite engineer here! 
Made a quick PR to support prefixing, in case it helps https://github.com/peterbourgon/g2s/pull/13
